add black to pre-commit hook & re-format py files (#569)

diff --git a/scripts/check-ci b/scripts/check-ci
--- a/scripts/check-ci
+++ b/scripts/check-ci
@@ -13,10 +13,15 @@ exit_() {
     exit 1
 }
 
-## Check whether source code has been formatted:
-if ! ./scripts/format-code --quiet --whatif; then
-    echo "code not formatted correctly, IGNORING FOR NOW!"
-    #exit_ "CI failed: please run ./scripts/format-code"
+## Check whether C/C++ source code has been formatted:
+if ! ./scripts/format-c-code --quiet --whatif; then
+    echo "C/C++ code not formatted correctly, IGNORING FOR NOW!"
+    #exit_ "CI failed: please run ./scripts/format-c-code"
+fi
+
+## Check whether Python source code has been formatted:
+if ! ./scripts/format-py-code --quiet --whatif; then
+    exit_ "CI failed: please run ./scripts/format-py-code"
 fi
 
 # Check whether all scripts pass ShellCheck:
