Work-in-progress port of SGX-LKL to use Open Enclave.

diff --git a/tools/sgx-lkl-disk b/tools/sgx-lkl-disk
--- a/tools/sgx-lkl-disk
+++ b/tools/sgx-lkl-disk
@@ -7,10 +7,14 @@ set -o pipefail
 SELF="$(basename ${BASH_SOURCE})"
 SELF_DIR="$( cd "$( dirname ${BASH_SOURCE} )" >/dev/null 2>&1 && pwd )"
 
-ALPINE_MAJOR=3.9
-ALPINE_VERSION=3.9.0
+ALPINE_MAJOR=3.10
+ALPINE_VERSION=3.10.0
 ALPINE_ARCH=x86_64
-ALPINE_TAR_SHA256="f82efed1a80c9af86c38bed10f3541c5588453b97684d767a5a3b0f3fa0e3f09"
+ALPINE_TAR_SHA256="ec3da7fb5f709a1ce912e6e31fccc5588420c5f1dcecc362c72c989532c1917a"
+#ALPINE_MAJOR=3.8
+#ALPINE_VERSION=3.8.2
+#ALPINE_ARCH=x86_64
+#ALPINE_TAR_SHA256="349d708d67ccbc22ffedc9eb87be539dbb64c4524756c0964187cb6a1aae27ac"
 
 VERBOSE_OUT=/dev/null
 CRYPTSETUP_VERBOSE_FLAGS=""
@@ -19,6 +23,14 @@ SYSDIRS=(dev mnt tmp sys run proc)
 
 USER=$(who am i | awk '{print $1}')
 GROUP=$(id -gn ${USER})
+
+# The lowest possible ext4 size seems to be ~140K. To be on the safe side, we require 512K.
+MIN_DISK_SIZE=524288
+
+BLOCK_SIZE=8192
+
+# mkfs options that reduce the filesystem overhead.
+MKFS_FLAGS="-m 0 -O ^has_journal,^resize_inode,sparse_super2"
 
 function usage() {
 cat << UsageMsg
@@ -35,6 +47,7 @@ Actions
  U, unmount                 Unmount MOUNTPOINT.
  h, help                    Print this help text.
  u, usage                   Print usage info.
+ M, measure                 Embed the root hash into enclave image.
 
 General options
  -V, --verbose              More verbose output.
@@ -42,6 +55,7 @@ General options
 Create ('create') options
  -x, --cleanup              Clean up downloads and Docker images that would
                             otherwise get cached.
+ -f, --force                Overwrite existing image file without asking.
  -a, --alpine=<alpine pkg>  Create disk with Alpine image as basis with the
                             specified package(s) installed. Multiple packages
                             must be separated by a whitespace.
@@ -54,12 +68,14 @@ Create ('create') options
       --nocontext           Build Docker image with no/a minimal build context.
  -i, --from-image=<path>    Create disk as a copy of the existing image at
                             <path>.
+ -t, --from-tarfile=<path>  Create disk as a filesystem containing the contents
+                            of the existing tarfile at <path>.
  -C, --copy=<path>          Create disk by copying directory contents or a
                             single file. Can be combined with --alpine,
                             --docker, and --from-image.
  -S, --size=bytes           Size of the disk in bytes. "k/K", "m/M", "g/G" can
                             be used as units.
- -e, --encrpyt              Enables dm-crypt disk encryption. All parameters
+ -e, --encrypt              Enables dm-crypt disk encryption. All parameters
                             below are passed on to cryptsetup as is. See
                             cryptsetup --help for more information on them.
       --cipher=<cipher>     Sets the dm-crypt cipher (Default: aes-xts-plain64)
@@ -98,6 +114,10 @@ Mount ('mount') options:
                             hash and IMAGEFILE.hashoffset to contain the offset
                             to the hash metadata.
 
+Measure ('measure') options:
+ --roothash=<path>          The path to the IMAGEFILE.roothash generated by
+                            --verity option.
+
 NOTES on --encrypt:
   1. --encrypt requires either --key-file or --passphrase to be specified.
   2. The chosen key or passphrase has to be provided to SGX-LKL via
@@ -126,6 +146,7 @@ Examples:
 
 sgx-lkl-disk create --size=100M --docker=./Dockerfile sgxlkl-disk.img
 sgx-lkl-disk create --size=100M --from-image=sgxlkl-disk.img sgxlkl-disk.img
+sgx-lkl-disk create --size=100M --from-tarfile=sgxlkl-fs.tar sgxlkl-disk.img
 sgx-lkl-disk create --size=100M --alpine="redis memcached" sgxlkl-disk.img
 sgx-lkl-disk create --size=100M --alpine="python" --copy=./my-python-app sgxlkl-disk.img
 sgx-lkl-disk create --size=100M --copy=./my-root --encrypt --key-file=./my-key sgxlkl-disk.img.enc
@@ -135,8 +156,16 @@ sgx-lkl-disk create --size=100M --copy=./my-root --verity sgxlkl-disk.img.vrt
 sgx-lkl-disk status sgxlkl-disk.img
 sgx-lkl-disk mount --mnt-point=./mnt-sgxlkl ./sgxlkl-disk.img
 sgx-lkl-disk unmount ./mnt-sgxlkl
+sgx-lkl-disk measure --roothash=sgxlkl-disk.img.roothash libsgxlkl.so
 UsageMsg
 }
+
+# Note: Disk creation also configures 8.8.8.8 as the nameserver.
+# Otherwise dialing out from the enclave does not work properly.
+IMG_BUILDENV_RESOLV="\
+nameserver 8.8.8.8
+nameserver 1.1.1.1
+"
 
 ALPINE_BUILDENV_TEMPLATE="\
 #!/bin/sh
@@ -146,8 +175,7 @@ set -e
 PATH=/usr/sbin:/sbin:/usr/bin:/bin
 
 cat << resolv > /etc/resolv.conf
-nameserver 8.8.8.8
-nameserver 1.1.1.1
+\${IMG_BUILDENV_RESOLV}
 resolv
 
 echo \"Updating Alpine package index...\"
@@ -160,7 +188,7 @@ to_cleanup=0
 function cleanup_echo() {
     if [[ "${to_cleanup}" == "0" ]]; then
         to_cleanup=1
-        echo "Cleaning up temporary files..."
+        #echo "Cleaning up temporary files..."
     fi
 }
 
@@ -245,7 +273,7 @@ function err_op() {
 }
 
 function err_create_op() {
-    echo "$SELF: Exactly one of --alpine, --docker, --from-image, --copy (combinable with others) is required with 'create'."
+    echo "$SELF: Exactly one of --alpine, --docker, --from-image, --from-tarfile, --copy (combinable with others) is required with 'create'."
     exit 126
 }
 
@@ -373,10 +401,10 @@ function create_from_alpine() {
 
     tmp_mnt_point=$(mktemp -d -t sgxlkl_tmp_mnt_XXX)
     tmp_buildenv=$(mktemp -t sgxlkl_tmp_buildenv_XXX)
-    echo "${ALPINE_BUILDENV_TEMPLATE}" | sed -e "s/\${alpine_pkgs}/${alpine_pkgs}/" > ${tmp_buildenv}
+    echo "${ALPINE_BUILDENV_TEMPLATE}" | sed -e "s/\${alpine_pkgs}/${alpine_pkgs}/" | sed -e "s/\${IMG_BUILDENV_RESOLV}/${IMG_BUILDENV_RESOLV}/" > ${tmp_buildenv}
 
     dd if=/dev/zero of="${disk_image}" count=$((${disk_size}/512)) ibs=512 &> ${VERBOSE_OUT}
-    mkfs.ext4 "${disk_image}" &> ${VERBOSE_OUT}
+    mkfs.ext4 $MKFS_FLAGS "${disk_image}" &> ${VERBOSE_OUT}
     sudo mount -t ext4 -o loop "${disk_image}" ${tmp_mnt_point}
     sudo tar -C ${tmp_mnt_point} -xf ${alpine_tar}
     if [[ ! -z "${copy_src}" ]]; then sudo cp -r ${copy_src} ${tmp_mnt_point}; fi
@@ -413,16 +441,20 @@ function create_from_docker() {
         docker build --rm=true -t ${docker_image} -f "${dockerfile}" "${docker_context}" > ${VERBOSE_OUT}
     fi
 
-    echo "Creating and exporting Docker container..."
-    docker_container_id=$(docker create ${docker_image})
-    tmp_docker_tar=$(mktemp -t sgxlkl_tmp_docker_tar_XXX)
-    docker export -o ${tmp_docker_tar} ${docker_container_id}
+    echo "Creating disk image file from Docker container..."
 
-    echo "Creating disk image file..."
+    # Store metadata for use in sgx-lkl-cfg tool.
+    docker image inspect ${docker_image} > ${disk_image}.docker
+    
+    docker_container_id=$(docker create ${docker_image})
+
     dd if=/dev/zero of="${disk_image}" count=$((${disk_size}/512)) ibs=512 &> ${VERBOSE_OUT}
-    mkfs.ext4 "${disk_image}" &> ${VERBOSE_OUT}
+    mkfs.ext4 $MKFS_FLAGS "${disk_image}" &> ${VERBOSE_OUT}
     sudo mount -t ext4 -o loop "${disk_image}" ${tmp_mnt_point};
-    sudo tar -C ${tmp_mnt_point} -xf ${tmp_docker_tar}
+
+    docker export ${docker_container_id} | sudo tar -C ${tmp_mnt_point} -xf - 
+
+    echo "${IMG_BUILDENV_RESOLV}" | sudo tee -a ${tmp_mnt_point}/etc/resolv.conf > /dev/null
     if [[ ! -z "${copy_src}" ]]; then sudo cp -r ${copy_src} ${tmp_mnt_point}; fi
     for sysdir in "${SYSDIRS[@]}"; do
         if [[ ! -e "${tmp_mnt_point}/${sysdir}" ]]; then
@@ -471,12 +503,31 @@ function create_from_image() {
     [[ ! -z "${tmp_image:-}" ]] && mv "${tmp_image}" "${disk_image}" || true
 }
 
+function create_from_tarfile() {
+    src_size=$(du -b "${image_src}" | cut -f1)
+    [[ "${src_size}" -gt "${disk_size}" ]] && err_image_src_size || true
+
+    echo "Creating base image with the contents from ${image_src}..." >&6
+    tar_filesize=`du -b ${image_src} | cut -f1`
+    tmp_mnt_point=$(mktemp -d -t sgxlkl_tmp_mnt_XXX)
+
+    block_count=$(((${disk_size} / ${BLOCK_SIZE}) + 1))
+
+    dd if=/dev/zero of=${disk_image} count="${block_count}" bs=${BLOCK_SIZE} status=none
+    mkfs.ext4 $MKFS_FLAGS -q ${disk_image}
+    sudo mkdir -p ${tmp_mnt_point}
+    sudo mount -t ext4 -o loop ${disk_image} ${tmp_mnt_point}
+    cat ${image_src} | sudo tar xp -C ${tmp_mnt_point}
+    echo "${IMG_BUILDENV_RESOLV}" | sudo tee -a  ${tmp_mnt_point}/etc/resolv.conf > /dev/null
+    sudo umount ${tmp_mnt_point}
+}
+
 function create_from_dir() {
     echo "Creating base image from directory/file ${copy_src%/.*}..."
     tmp_mnt_point=$(mktemp -d -t sgxlkl_tmp_mnt_XXX)
 
     dd if=/dev/zero of="${disk_image}" count=$((${disk_size}/512)) ibs=512 &> ${VERBOSE_OUT}
-    mkfs.ext4 "${disk_image}" &> ${VERBOSE_OUT}
+    mkfs.ext4 $MKFS_FLAGS "${disk_image}" &> ${VERBOSE_OUT}
     sudo mount -t ext4 -o loop "${disk_image}" ${tmp_mnt_point}
     sudo cp -r ${copy_src} ${tmp_mnt_point}
     for sysdir in "${SYSDIRS[@]}"; do
@@ -613,15 +664,30 @@ function create() {
     disk_size=$(to_bytes "$sz")
     disk_size=$(( (${disk_size} + 511) / 512 * 512)) # 512 byte alignment
 
-    if [[ -e ${disk_image} ]]; then warn_exists ${disk_image}; fi
+    if [[ $disk_size -lt $MIN_DISK_SIZE ]]; then
+        echo "Requested disk size $sz too small, increasing to $MIN_DISK_SIZE bytes"
+        disk_size=$MIN_DISK_SIZE
+    fi
 
-    if [[ ! $(($a + $d + $im)) == 1 ]] && [[ -z "${copy_src}" ]]; then err_create_op; # Exactly one of the below ops has to be specified.
+    if [[ -e ${disk_image} ]] && [[ ${force} != 1 ]]; then warn_exists ${disk_image}; fi
+
+    # Check if we can detect the host DNS server when generating /etc/resolv.conf for the image
+    if [[ "$d" = 1 ]] || [[ "$tar" = 1 ]] || [[ "$a" = 1 ]]; then
+        if [[ -x "$(command -v systemd-resolve)" ]]; then
+            dns_server=$(systemd-resolve --status | grep -E -o "DNS Servers: ([0-9]{1,3}[\.]){3}[0-9]{1,3}" | cut -f2- -d: | cut -f2- -d' ')
+            echo "Using detected host DNS server in /etc/resolv.conf: ${dns_server}"
+            IMG_BUILDENV_RESOLV="nameserver ${dns_server}"
+        fi
+    fi
+
+    if [[ ! $(($a + $d + $im + $tar)) == 1 ]] && [[ -z "${copy_src}" ]]; then err_create_op; # Exactly one of the below ops has to be specified.
     elif [ "$a" = 1 ]; then create_from_alpine;
     elif [ "$d" = 1 ]; then create_from_docker;
     elif [ "$im" = 1 ]; then create_from_image;
+    elif [ "$tar" = 1 ]; then create_from_tarfile;
     else create_from_dir; fi
 
-    luks_header_size=$(to_bytes "2M") # LUKS header size should be <= 2 MiB
+    luks_header_size=$(to_bytes "6M") # LUKS header size should be <= 6 MiB
 
     # TODO Proper calculation for integrity overhead, currently 15%
     [[ "$i" == 1 ]] && integrity_overhead=$((${disk_size} / 100 * 15)) || integrity_overhead=0
@@ -642,7 +708,7 @@ function create() {
     elif [ "$i" = 1 ]; then integrity; # encryption + integrity (via dm-integrity) is handled within 'encrypt'
     elif [ "$v" = 1 ]; then verity; fi # encryption + verity (via dm-verity) is handled within 'encrypt'
 
-    echo "Succesfully created ${disk_image}."
+    echo "Succesfully created ${disk_image}." >&6
 }
 
 function status() {
@@ -762,6 +828,15 @@ function unmount() {
     echo "Successfully unmounted ${mnt_point}";
 }
 
+function measure() {
+    req oesethash
+
+    echo "Embedding root hash from ${roothash_file} into ${disk_image}..."
+
+    root_hash=$(cat ${roothash_file})
+    oesethash ${disk_image} disk_dm_verity_root_hash ${root_hash}
+}
+
 # <Short option>,<Long option>,<(no-argument)|: (mandatory)|:: (optional)>
 OPTIONS="\
 U,usage, \
@@ -769,12 +844,15 @@ h,help, \
 M,mnt-point,: \
 ,mnt-options,: \
 x,cleanup, \
+f,force, \
 V,verbose, \
+Q,quiet, \
 a,alpine,: \
 d,docker,: \
 ,nocontext, \
 C,copy,: \
 i,from-image,: \
+t,from-tarfile,: \
 e,encrypt, \
 ,cipher,: \
 p,passphrase,: \
@@ -785,8 +863,13 @@ H,hash,: \
 v,verity,:: \
 I,integrity,:: \
 S,size,: \
+,roothash,: \
 "
-c=0 s=0 m=0 u=0 a=0 d=0 e=0 i=0 v=0 im=0 sz=0 k=0 copy_src=""
+
+c=0 s=0 m=0 u=0 M=0 a=0 d=0 e=0 i=0 v=0 im=0 tar=0 sz=0 k=0 copy_src="" force=0
+
+# Exit with a help text if no command line parameters are given
+[[ $# -eq 0 ]] && usage && exit 0
 
 case "$1" in
     u|h|usage|help)
@@ -809,6 +892,10 @@ case "$1" in
         u=1
         shift
         ;;
+    M|measure)
+        M=1
+        shift
+        ;;
 esac
 
 
@@ -826,6 +913,8 @@ if ! ARGS=$(getopt --options=$SHORTOPTS --longoptions=$LONGOPTS --name "$0" -- "
 fi
 eval set -- "$ARGS"
 
+exec 6>&1
+
 while true; do
     case "$1" in
         -u|-h|--usage|--help)
@@ -841,6 +930,15 @@ while true; do
             exec 5>&1
             VERBOSE_OUT=/dev/fd/5
             CRYPTSETUP_VERBOSE_FLAGS="-v --debug"
+            shift
+            ;;
+        -Q|--quiet)
+            # Supress some ouput, which is useful in scripts
+            exec 6>/dev/null
+            shift
+            ;;
+        -f|--force)
+            force=1
             shift
             ;;
         -a|--alpine)
@@ -866,12 +964,18 @@ while true; do
             ;;
         -C|--copy)
             if [[ $2 == -* ]]; then err_req_arg $1; fi
-            if [[ -d "$2" ]]; then copy_src="$2/."; else copy_src="$2"; fi
+            copy_src="$2"
             shift 2
             ;;
         -i|--from-image)
             if [[ $2 == -* ]]; then err_req_arg $1; fi
             im=1
+            image_src=$2
+            shift 2
+            ;;
+        -t|--from-tarfile)
+            if [[ $2 == -* ]]; then err_req_arg $1; fi
+            tar=1
             image_src=$2
             shift 2
             ;;
@@ -943,6 +1047,11 @@ while true; do
             mnt_options="$2"
             shift 2
             ;;
+        --roothash)
+            if [[ $2 == -* ]]; then err_req_arg $1; fi
+            roothash_file="$2"
+            shift 2
+            ;;
         --)
             shift
             break
@@ -961,8 +1070,9 @@ fi
 
 [[ "$u" == 1 ]] && mnt_point=$1 || disk_image=$1
 
-if [[ ! $(($c + $s + $m + $u)) == 1 ]]; then err_op; # Exactly one of the below ops has to be specified.
+if [[ ! $(($c + $s + $m + $u + $M)) == 1 ]]; then err_op; # Exactly one of the below ops has to be specified.
 elif [ "$c" = 1 ]; then create;
 elif [ "$s" = 1 ]; then status;
 elif [ "$m" = 1 ]; then mount;
-elif [ "$u" = 1 ]; then unmount; fi
+elif [ "$u" = 1 ]; then unmount;
+elif [ "$M" = 1 ]; then measure; fi
